### ISSUE TITLE
Problem installing 

### ISSUE THREAD

**Issue by markengelhardt** [boxcar/boxcar-cordova-plugin#4]
When I attempt 

`cordova plugin add https://github.com/boxcar/boxcar-cordova-plugin`

I get this error: 
`
cordova plugin add https://github.com/boxcar/boxcar-cordova-plugin
(node:57245) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Failed to fetch plugin https://github.com/boxcar/boxcar-cordova-plugin via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: git+https://github.com/boxcar/boxcar-cordova-plugin.git.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mark/.npm/_logs/2018-01-22T00_45_42_676Z-debug.log
(node:57245) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

I am running on Mac OS 10.12.6 and cordova is version 8.0.0

Any suggestions?

**Comment by prefiks** [comment]
Hi,

I added package.json as is required by new cordova for plugins, so you should no longer should get that error.
